[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "discrete"
version = "0.1"
dependencies = ["matplotlib", "random", "numpy"]

[tool.hatch.build.targets.wheel]
packages = ["life"]